/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.newardassociates.demo;

// {{## BEGIN embedded ##}}
import org.python.core.PyObject;
import org.python.util.PythonInterpreter;

public class App {
  public static void main(String[] args) {
    try(PythonInterpreter pyInterp = new PythonInterpreter()) {
      pyInterp.exec("print('Hello Python World!')");

      PyObject result = pyInterp.eval("2+2");
    }
  }
}
// {{## BEGIN embedded ##}}

